apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-app
  template:
    metadata:
      labels:
        app: kitchen-app
    spec:
      containers:
        - name: kitchen-app
          image: aalyankhan029/kitchen-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
        # Optional: mount configmap too
            - name: config-volume
              mountPath: "/etc/config"
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: postgres-secret
        - name: config-volume
          configMap:
            name: postgres-config

